fix error and log when LMS is too short (#415)
In
https://github.com/Sundhedsdatastyrelsen/ehdsi/actions/runs/21934336259/job/63345195619,
we got the following error:

```
java.lang.StringIndexOutOfBoundsException: Range [126, 26) out of bounds for length 26
        ...
	at java.base/java.lang.String.substring(String.java:2823)
	at dk.sundhedsdatastyrelsen.ncpeh.locallms.Specs$Table.lambda$parseRow$0(Specs.java:36)
        ...
	at dk.sundhedsdatastyrelsen.ncpeh.locallms.Specs$Table.parseRow(Specs.java:40)
	at dk.sundhedsdatastyrelsen.ncpeh.locallms.LocalLmsLoader.parseAndLoadRawData(LocalLmsLoader.java:51)
	at dk.sundhedsdatastyrelsen.ncpeh.locallms.LocalLmsLoader.fetchData(LocalLmsLoader.java:26)
	at dk.sundhedsdatastyrelsen.ncpeh.FmkIT.initialiseLmsData(FmkIT.java:87)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

This pr fixes that error, and logs the line from LMS that caused it, so
we can understand what's going on.

LMS is a fixed length file format, so we should never see lines that are
too short.